# api/config/routes.yaml
auth:
    path: /auth
    methods: ['POST']

# config/routes.yaml
api_login_check:
    path: /api/login_check

authentication_token:
    path: /authentication_token
    methods: ['POST']