

name: CI

on:
  #push:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Run tests
      run: |
        # run tests here
        # example: npm test
    
    - name: Build project
      run: |
        cd client
        npm run dev
        # build your project here
        # example: npm run build

    - name: Deploy
      run: |
        # deploy your project here
        # example: scp -r build user@server:/path/to/deploy

  ci-back:
    name: CI Back
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: pboitelle
        password: ${{ secrets.DOCKER_APP }}
    - name: Checkout code
      run: docker build up -d

  example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
        echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

    - name: Print environment variables
      run: |
        echo "API_URL=$API_URL"
        echo "API_TOKEN=$API_TOKEN"


  publish-docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: pboitelle
        password: ${{ secrets.DOCKER_APP }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: pboitelle/app:latest

